### ISSUE TITLE
Copper nuggets conflict

### ISSUE THREAD

**Issue by alexcrafteroreal** [TeamAOF/All-of-Fabric-4#17]
Hi!
There is a conflict with the copper nuggets. There is two types of copper nuggets.
When you try to craft an output servo you can´t because it asks for a copper nugget that you can´t craft.

**Comment by dandin87** [comment]
This is fixed in 0.0.6 (unreleased) and is fixed on the server as soon as I update it to 0.0.5 shortly. for now if you want to fix it in single player, you can open kubejs/server_scripts/balancing.js and after this line, 
`events.listen("recipes", function (event) {`
add this line. 
`  event.remove({ output: "charm:copper_nugget" });`
This will also prevent Charm Copper Lanterns from being craftable, but this will actually end up in unification.js in the next update, and the other part of it is to replace all charm:copper_nugget inputs. but for now this will get you by. You can also smelt down copper gear to get IndRev:copper_nuggets.

**Comment by lothsun** [comment]
Any ideas on when the update will be released?
