### ISSUE TITLE
Server crash.

### ISSUE THREAD

**Issue by XsFrozdY** [TeamAOF/All-of-Fabric-4#26]
Filename
AllofFabric4Server-0.0.5.zip
Uploaded by
HeyAmAK9
Uploaded
Jun 30, 2021
Game Version
1.17
Storlek
12,55 KB
Downloads
1 830
MD5
c2b33f49d2ab4a26fcafa68927a21051
[latest.log](https://github.com/TeamAOF/All-of-Fabric-4/files/6809737/latest.log)

**Comment by dandin87** [comment]
You need to use Java 16 for Minecraft 1.17

**Comment by XsFrozdY** [comment]
Weird then, since I CAN play the modpack through curseforge without issues, just not run the server, but I'll try to find Java 16, not gonna be easy because... you know... they have like 984679348679867 branches...

**Comment by dandin87** [comment]
Yes, Curseforge uses the vanilla Launcher which has java16 built in. In the server-starter-config.yaml file you can specify the path to that java location which I think is something like program files/Minecraft launcher/something or you can install jave 16 and make sure you choose to set the PATH variable so that the server starter sees Java 16 is installed and then you will not need to change the config. 
https://adoptopenjdk.net/?variant=openjdk16&jvmVariant=hotspot
